### PR TITLE
This branch is ready to review

### PR DESCRIPTION
**Pull request by danmontielh**

### CODE REVIEW

**Review by oluwoleilesanmi — CHANGES_REQUESTED** [review]
@madcido @danmontielh well done your layout is well aligned. make below changes and you will be good to go.
- Problem is below image doesnt display on Github previewer attempt fix
nytone
- To-recreate paste this [Link](https://github.com/madcido/nyt-clone/blob/development/index.html) in [Github Previewer](https://htmlpreview.github.io)
- Reason-to-fix not every visitor on your repo will clone the repo to see what it looks like.

- Improve spacing of section below
nyttwo

**Review by oluwoleilesanmi — APPROVED** [review]
@danmontielh @madcido well done :+1:  :1st_place_medal: proceed.

**Comment by nidalaa** [comment]
Re: stickler issues.

@danmontielh @madcido could you do the following steps in this order and see if it works?

1. remove .stickler.yml file from master
2. add .stickler.yml to this branch

It should not change you review result @oluwoleilesanmi . I just want to figure out what can help in different scenarios, so we can avoid it in the future.

**Comment by madcido** [comment]
@nidalaa 

Done as you asked: removed the stickler from master and then added it to development branch. It seems some error persists. Anything else I can try?

**Comment by nidalaa** [comment]
@madcido it looks like you used tabs for indentation and it causes some errors, can you change it to spaces, please?

**Comment by madcido** [comment]
@nidalaa 
It seems fine now. I'm pretty sure I just copied this stickler from your repo, I don't recall changing it before... Maybe you should check if the original one is using space or tab for the indentation.
Anyway, thanks for the help!

**Comment by nidalaa** [comment]
@madcido the original uses spaces. How did you copy the file? Just its content from Github or did you pull files to your machine and copied from there? Also - maybe your text editor changes spaces to tabs?

**Comment by madcido** [comment]
@nidalaa 
I copied the content from Github. Selected everything, ctrl c, created a new file, ctrl v, saved as ".stickler.yml". But you nailed it: I'm pretty sure my text editor changed the space to tab for better indentation or something like that.

**Pull request merged**
